FROM python:3-alpine

WORKDIR /app

RUN pip install --upgrade pip
RUN pip install flask
RUN pip install gunicorn
RUN pip install psycopg2-binary

ENV FLASK_APP=app.py
ENV PYTHONDONTWRITEBYTECODE=1
ENV FLASK_DEBUG=1

# CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"] for production
CMD ["flask", "run", "--host=0.0.0.0", "--reload"]